[package]
name = "iridium_weatherstation"
version = "0.1.0"
authors = ["Willi Kappler, grandor@gmx.de"]

[lib]
name = "station_util"
path = "src/station_util.rs"

[dependencies]
time = "0.1"
flexi_logger = "0.5"
log = "0.3"
clap = "2.4"
quick-error = "1.1"
regex = "0.1"
chrono = "0.2"
# half = "0.1.0"

[dependencies.mysql]
version = "*"
default-features = false
features = ["socket"]
